version: '3'
services:
 app:
   ports:
     - "10082:80"
   build: ./
   container_name: php_app
   volumes:
     - ./src:/var/www/html
  
 db:
   image: mysql:5.7
   container_name: php_db
   command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
   volumes:
     - ./docker/db/data:/var/lib/mysql
     - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
   environment:
     - DB_CONNECTION=mysql
     - DB_HOST=db
     - DB_PORT=3307
     - DB_DATABASE=${DB_NAME:-php_db}
     - DB_USERNAME=${DB_USER:-php_pass}
     - DB_PASSWORD=${DB_PASS:-php_pass}
     
 phpmyadmin:
   image: phpmyadmin/phpmyadmin
   environment:
     - PMA_ARBITRARY=1
     - PMA_HOST=php_db
     - PMA_USER=php_pass
     - PMA_PASSWORD=php_pass
   links:
     - db
   ports:
      - 8082:80
   volumes:
      - /sessions